#!/usr/bin/env python3
"""Independent unbounded Python integer model; reproducible vector generation."""
import json
import pathlib
import random

ROOT = pathlib.Path(__file__).resolve().parents[1]
SEED = 0x20260907

def dot(a, b):
    assert len(a) == len(b) == 8
    assert all(-128 <= x <= 127 for x in a+b)
    return sum(x*y for x,y in zip(a,b))

def cases():
    directed = [
        ('zeros', [0]*8, [0]*8),
        ('positive', list(range(1,9)), list(range(8,0,-1))),
        ('negative', [-x for x in range(1,9)], list(range(1,9))),
        ('cancel', [1,-1]*4, [127]*8),
        ('max_positive', [-128]*8, [-128]*8),
        ('max_negative', [-128]*8, [127]*8),
        ('positive_extreme', [127]*8, [127]*8),
        ('last_only', [0]*7+[-128], [0]*7+[127]),
        ('mixed', [-128,127,-1,0,1,9,-37,65], [127,-128,1,99,-1,-4,23,-12]),
        ('both_negative', [-3]*8, [-7]*8),
    ]
    rng = random.Random(SEED)
    directed += [(f'random_{i:03d}', [rng.randint(-128,127) for _ in range(8)],
                  [rng.randint(-128,127) for _ in range(8)]) for i in range(256)]
    return [dict(id=i,name=n,a=a,b=b,expected=dot(a,b)) for i,(n,a,b) in enumerate(directed)]

def main():
    all_cases = cases()
    dest = ROOT/'verification'/'vectors'
    dest.mkdir(parents=True, exist_ok=True)
    (dest/'cases.json').write_text(json.dumps({'seed':SEED,'cases':all_cases},indent=2)+'\n')
    words=[]
    for c in all_cases:
        words += c['a']+c['b']+[c['expected']]
    (dest/'cases.hex').write_text(''.join(f'{v & 0xffffffff:08x}\n' for v in words))
    fw = ROOT/'firmware'
    fw.mkdir(exist_ok=True)
    header=['/* Generated by scripts/reference.py; do not edit. */',
            '#define CASE_COUNT 26',
            'struct vector_case { signed char a[8], b[8]; int expected; };',
            'static const struct vector_case test_cases[CASE_COUNT] = {']
    for c in all_cases[:26]:
        header.append('  {{'+','.join(map(str,c['a']))+'},{'+','.join(map(str,c['b']))+'},'+str(c['expected'])+'},')
    header.append('};\n')
    (fw/'vectors.h').write_text('\n'.join(header))
    print(f'PASS: generated {len(all_cases)} independent reference vectors, seed {SEED:08x}')

if __name__ == '__main__': main()
